import { useState } from 'react';
import Swal from 'sweetalert2';
import { Icon, PageHead } from '../components/Shell';
import { SCENARIOS } from '../lib/data';
import type { TranscriptEntry, ViewType } from '../types';

interface Props { go: (v: ViewType) => void; transcripts: TranscriptEntry[]; onDelete: (id: string) => void; }

function tColor(s: number) { return s >= 80 ? 'var(--score-hi)' : s >= 60 ? 'var(--score-mid)' : 'var(--score-lo)'; }
function scenInfo(id: string) { return SCENARIOS.find(x => x.id === id) ?? { en: id, ko: '', icon: '💬', level: 'beg' as const }; }

function downloadPdf(t: TranscriptEntry) {
  const sc = scenInfo(t.scenario);
  const scoreColor = t.score >= 80 ? '#16a34a' : t.score >= 60 ? '#d97706' : '#dc2626';
  const linesHtml = t.lines.map(([who, line]) => {
    const isMimic = who === 'Mimic';
    return `<div class="line ${isMimic ? 'mimic-line' : 'me-line'}">
      <div class="who">${isMimic ? '🦜 Mimic' : '👤 Me'}</div>
      <div class="text">${line.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
    </div>`;
  }).join('');

  const html = `<!DOCTYPE html><html lang="ko"><head><meta charset="utf-8">
<title>Mimic · ${sc.en}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f3f4f6; padding: 32px 16px; }
  .card { background: #fff; border-radius: 16px; padding: 40px; max-width: 660px; margin: 0 auto; box-shadow: 0 4px 16px rgba(0,0,0,0.08); }
  .header { border-bottom: 2px solid #dcfce7; padding-bottom: 20px; margin-bottom: 28px; }
  .brand { font-size: 12px; color: #16a34a; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; margin-bottom: 8px; }
  h1 { font-size: 24px; font-weight: 800; color: #111827; }
  .meta { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 12px; }
  .meta span { font-size: 13px; color: #6b7280; display: flex; align-items: center; gap: 4px; }
  .score-badge { background: #dcfce7; color: ${scoreColor}; font-weight: 800; padding: 3px 12px; border-radius: 100px; font-size: 14px; }
  .line { margin-bottom: 14px; padding: 14px 18px; border-radius: 12px; }
  .mimic-line { background: #f0fdf4; border-left: 3px solid #86efac; }
  .me-line { background: #f9fafb; border-left: 3px solid #d1d5db; }
  .who { font-size: 11.5px; font-weight: 700; color: #9ca3af; margin-bottom: 5px; letter-spacing: 0.04em; }
  .mimic-line .who { color: #16a34a; }
  .text { font-size: 15px; line-height: 1.65; color: #111827; }
  .footer { text-align: center; margin-top: 28px; font-size: 12px; color: #9ca3af; }
  @media print {
    body { background: white; padding: 0; }
    .card { box-shadow: none; border-radius: 0; padding: 28px; }
  }
</style></head><body>
<div class="card">
  <div class="header">
    <div class="brand">🦜 MIMIC — 회화 대본</div>
    <h1>${sc.icon} ${sc.en} <span style="font-weight:500;color:#6b7280;font-size:18px">· ${sc.ko}</span></h1>
    <div class="meta">
      <span>📅 ${t.date}</span>
      <span>발음 점수 <span class="score-badge">${t.score}점</span></span>
      <span>💬 ${t.lines.length}줄</span>
    </div>
  </div>
  ${linesHtml}
  <div class="footer">Generated by Mimic · ${new Date().toLocaleDateString('ko-KR')}</div>
</div>
</body></html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 600);
  }
}

export default function Transcript({ go: _go, transcripts, onDelete }: Props) {
  const [scen, setScen] = useState('all');
  const [sort, setSort] = useState<'recent' | 'score'>('recent');

  let list = transcripts.filter(t => scen === 'all' || t.scenario === scen);
  list = [...list].sort((a, b) =>
    sort === 'recent' ? b.date.localeCompare(a.date) : b.score - a.score,
  );

  return (
    <div style={{ padding: '34px 40px 60px', maxWidth: 880, margin: '0 auto' }}>
      <PageHead icon="📝" title="대본 다운로드" sub="지난 회화를 다시 보고 .txt로 저장해 복습하세요" />

      <div style={{ display: 'flex', gap: 10, marginBottom: 20, flexWrap: 'wrap' }}>
        <select value={scen} onChange={e => setScen(e.target.value)}
          style={{ border: '1.5px solid var(--border-strong)', background: 'var(--surface)', borderRadius: 'var(--r-pill)', padding: '9px 40px 9px 16px', fontSize: 14, color: 'var(--text)', cursor: 'pointer' }}>
          <option value="all">전체 시나리오</option>
          {SCENARIOS.map(s => <option key={s.id} value={s.id}>{s.en} · {s.ko}</option>)}
        </select>
        <div className="segment">
          {([['recent', '최근순'], ['score', '점수순']] as const).map(([k, l]) => (
            <button key={k} className={sort === k ? 'on' : ''} onClick={() => setSort(k)}>{l}</button>
          ))}
        </div>
      </div>

      {list.length === 0 ? (
        <div className="card" style={{ padding: '60px 20px', textAlign: 'center', borderRadius: 'var(--r-lg)' }}>
          <div style={{ fontSize: 40 }}>📝</div>
          <h3 style={{ margin: '12px 0 4px' }}>아직 대본이 없어요</h3>
          <p style={{ color: 'var(--text-3)', margin: 0 }}>회화를 완료하면 여기에 대본이 자동으로 저장돼요.</p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {list.map((t, i) => {
            const sc = scenInfo(t.scenario);
            return (
              <div key={t.id} className="card" style={{ padding: '18px 22px', borderRadius: 'var(--r-lg)', animation: `fadeUp .4s ${i * 0.04}s` }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 13 }}>
                    <div style={{ width: 46, height: 46, borderRadius: 'var(--r-md)', background: `var(--lv-${sc.level}-bg)`, display: 'grid', placeItems: 'center', fontSize: 23 }}>{sc.icon}</div>
                    <div>
                      <div style={{ fontWeight: 800, fontSize: 16 }}>{sc.en} <span style={{ color: 'var(--text-3)', fontWeight: 600, fontSize: 13.5 }}>· {sc.ko}</span></div>
                      <div style={{ fontSize: 12.5, color: 'var(--text-3)' }}>{t.date}</div>
                    </div>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 14 }}>
                    <div style={{ textAlign: 'right' }}>
                      <div style={{ fontSize: 11, color: 'var(--text-3)' }}>발음</div>
                      <div style={{ fontWeight: 800, fontSize: 19, color: tColor(t.score) }}>{t.score}</div>
                    </div>
                    <button className="btn btn-soft btn-sm" onClick={() => downloadPdf(t)}>
                      <Icon name="download" size={16} /> PDF
                    </button>
                    <button
                      className="btn btn-danger btn-sm"
                      onClick={async () => {
                        const res = await Swal.fire({
                          title: '대본 삭제',
                          text: '이 대본을 삭제할까요? 되돌릴 수 없어요.',
                          icon: 'warning',
                          showCancelButton: true,
                          confirmButtonText: '삭제',
                          cancelButtonText: '취소',
                          confirmButtonColor: '#ef4444',
                          cancelButtonColor: '#6b7280',
                        });
                        if (res.isConfirmed) onDelete(t.id);
                      }}
                      style={{ padding: '6px 10px' }}
                      title="삭제"
                    >
                      <Icon name="x" size={15} />
                    </button>
                  </div>
                </div>
                <div style={{ marginTop: 14, paddingTop: 14, borderTop: '1px dashed var(--border)', display: 'flex', flexDirection: 'column', gap: 4 }}>
                  {t.lines.slice(0, 2).map(([who, line], j) => (
                    <div key={j} style={{ fontSize: 13.5, color: 'var(--text-2)' }}>
                      <b style={{ color: who === 'Mimic' ? 'var(--brand-strong)' : 'var(--text)' }}>{who === 'Mimic' ? 'Mimic' : 'Me'}</b>
                      <span style={{ color: 'var(--text-3)' }}> : {line}</span>
                    </div>
                  ))}
                  {t.lines.length > 2 && (
                    <div style={{ fontSize: 12, color: 'var(--text-3)' }}>+{t.lines.length - 2}개 더…</div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
